//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartesTrabajo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public Cliente()
        {
            this.Parte_Trabajo = new HashSet<Parte_Trabajo>();
        }
    
        public int IdCliente { get; set; }
        public string Nombre { get; set; }
        public string Nota { get; set; }
    
        public virtual ICollection<Parte_Trabajo> Parte_Trabajo { get; set; }
    }
}
