//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartesTrabajo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public Empleado()
        {
            this.Partes = new HashSet<Parte>();
        }
    
        public int IdEmpleado { get; set; }
        public string Nombre { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<Parte> Partes { get; set; }
    }
}
