//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartesTrabajo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parte
    {
        public Parte()
        {
            this.Parte_Trabajo = new HashSet<Parte_Trabajo>();
        }
    
        public int IdParte { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<double> Tiempo { get; set; }
        public Nullable<int> IdEmpleado { get; set; }
        public Nullable<bool> Modificado { get; set; }
        public string Motivo_Mod { get; set; }
        public string Nota { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual ICollection<Parte_Trabajo> Parte_Trabajo { get; set; }
    }
}
